---
version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 99
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 99
  - directory: "/"
    package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
