---
dist: xenial
env:
  global:
    SSH_KEY_FILENAME: id_rsa_ferrarimarco_github_io
    NOKOGIRI_USE_SYSTEM_LIBRARIES: true
services:
  - docker
language: shell
os: linux
jobs:
  fast_finish: true
  include:
    - name: "super-linter"
      language: shell
      script: make super-linter
      stage: linting
    - stage: build
      script:
        - make build-prod
    - stage: deploy
      if: branch = master
      script:
        - set -eo pipefail
        - echo "$SSH_PRIVATE_KEY" > "$SSH_KEY_FILENAME"
        - chmod 600 "$SSH_KEY_FILENAME"
        - make deploy
