---
name: Dependabot automation

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve the PR
        run: gh pr review --approve "${PR_URL}"
      - name: Enable auto-merge for patch updates PR
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch'
          || steps.metadata.outputs.dependency-names == '@babel/core'
          || steps.metadata.outputs.dependency-names == '@babel/preset-env'
          || steps.metadata.outputs.dependency-names == '@babel/register'
          || steps.metadata.outputs.dependency-names == '@babel/traverse'
          || steps.metadata.outputs.dependency-names == 'actions/checkout'
          || steps.metadata.outputs.dependency-names == 'css-loader'
          || steps.metadata.outputs.dependency-names == 'html-webpack-plugin'
          || steps.metadata.outputs.dependency-names == 'sass'
          || steps.metadata.outputs.dependency-names == 'super-linter/super-linter'
          || steps.metadata.outputs.dependency-names == 'webpack-merge'
          || steps.metadata.outputs.dependency-names == 'webpack'
        run: gh pr merge --auto --squash --delete-branch "${PR_URL}"
...
